apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  {{- range $path, $bytes := .Files.Glob "sql-files/*.sql" }}
  {{ base $path }}: |
{{ $bytes | toString | indent 4 }}
  {{- end }}