apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  password: YWRtaW4K

---

apiVersion: v1
kind: Secret
metadata:
  name: airflow-credentials
type: Opaque
data:
  password: YWlyZmxvdwo=