apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  labels:
    app: postgres
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5432
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-master
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
    apps.kubernetes.io/pod-index: "0"

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-read-replica
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
    apps.kubernetes.io/pod-index:
